server:
  port: 8091
  error:
    include-message: always
    include-binding-errors: always

spring:
  application:
    name: user-service

eureka:
  client:
    service-url:
      defaultZone: http://admin:admin@localhost:8761/eureka/

axon:
  serializer:
    events: jackson
